name: main3.9
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit   # Optional: Add if using GPU, or leave it out for CPU-only installs
  - pandas
  - tqdm
  - tensorboard
  - pillow
  - requests
  - setuptools
  - typing-extensions
  - zlib
